language: php

php:
  - 5.6
  - hhvm

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS akuntansi;" -uroot

install:
  - composer install;

before_script:
  - php artisan migrate:refresh --seed

script: phpunit