language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS akuntansi;" -uroot

install:
  - composer install

before_script:
  - php artisan migrate:refresh --seed --force

script: phpunit